"""Redraw the native ablation from the recorded 8db summary, without refitting.

Usage: python build_native_ablation.py
The main figure contains the four matched LOPO AUCs. Routing gains and
named per-pool values are retained in the appendix. Source numbers and
protocol are read unchanged from ../figures/native_feature_ablation.json.
"""

import hashlib
import json
import shutil
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch


HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "figures/native_feature_ablation.json"
CELLS = ("L22_last", "L22_agg", "L35_last", "L35_agg")
POOLS = (
    ("striviaqa", "Speech TriviaQA"),
    ("swebq", "Speech Web Questions"),
    ("sllama", "Speech Llama Questions"),
    ("sdqa", "SD-QA"),
    ("sreason", "Reasoning QA (zh)"),
)
SINGLE, AGGREGATE = "#AAB2BC", "#286CAA"
INK, MUTED = "#20252B", "#56616E"
XS = (0.0, 0.38, 1.02, 1.40)


def number(value, digits=3, signed=False):
    rounded = Decimal(str(value)).quantize(
        Decimal(1).scaleb(-digits), rounding=ROUND_HALF_UP
    )
    return format(rounded, f"+.{digits}f" if signed else f".{digits}f")


def save_figure(fig, name):
    folder = HERE / "figures"
    mirror = HERE.parent / "figures"
    folder.mkdir(parents=True, exist_ok=True)
    mirror.mkdir(parents=True, exist_ok=True)
    fig.savefig(folder / f"{name}.pdf", bbox_inches="tight")
    fig.savefig(folder / f"{name}.png", dpi=220, bbox_inches="tight")
    for suffix in ("pdf", "png"):
        shutil.copyfile(folder / f"{name}.{suffix}", mirror / f"{name}.{suffix}")
    plt.close(fig)


def base_figure(title, ylabel):
    fig, ax = plt.subplots(figsize=(6.5, 2.8))
    fig.subplots_adjust(left=0.12, right=0.98, bottom=0.22, top=0.73)
    fig.text(0.12, 0.98, title, fontsize=12, weight="bold", va="top")
    fig.legend(
        [Patch(facecolor=SINGLE), Patch(facecolor=AGGREGATE)],
        ["Single state", "Three-position aggregate"],
        loc="upper left", bbox_to_anchor=(0.105, 0.895),
        frameon=False, ncol=2, fontsize=10, handlelength=1.35,
        columnspacing=1.8,
    )
    ax.set_xticks((0.19, 1.21), ("L22 (middle layer)", "L35 (final layer)"))
    ax.set_xlim(-0.34, 1.74)
    ax.set_ylabel(ylabel, labelpad=7)
    ax.tick_params(axis="both", length=0, pad=7)
    ax.set_axisbelow(True)
    ax.grid(axis="y", color="#E6E9ED", linewidth=0.6)
    ax.grid(axis="x", visible=False)
    return fig, ax


def make_auc_figure(data):
    fig, ax = base_figure(
        "Aggregation improves failure prediction at L22",
        "Failure-prediction AUC",
    )
    ax.set_ylim(0.49, 0.775)
    ax.set_yticks((0.50, 0.55, 0.60, 0.65, 0.70))
    for i, (x, key) in enumerate(zip(XS, CELLS)):
        value = data[key]["auc"]["ext5_mean"]
        ax.bar(x, value - 0.5, bottom=0.5, width=0.29,
               color=AGGREGATE if i % 2 else SINGLE, zorder=3)
        ax.text(x, value + 0.006, number(value), ha="center", va="bottom",
                fontsize=11, color=INK)
    for i in (0, 2):
        gain = (data[CELLS[i + 1]]["auc"]["ext5_mean"]
                - data[CELLS[i]]["auc"]["ext5_mean"])
        ax.annotate("", xy=(XS[i + 1], 0.738), xytext=(XS[i], 0.738),
                    arrowprops={"arrowstyle": "->", "color": AGGREGATE,
                                "linewidth": 1.1})
        ax.text((XS[i] + XS[i + 1]) / 2, 0.747,
                number(gain, 2, signed=True), ha="center", va="bottom",
                fontsize=10.5, color=AGGREGATE)
    ax.axhline(0.5, color=MUTED, lw=0.8)
    ax.text(1.73, 0.504, "chance", ha="right", va="bottom",
            color=MUTED, fontsize=8.5)
    save_figure(fig, "native_feature_ablation")


def make_routing_figure(data):
    fig, ax = base_figure(
        "Routing benefit at a 30% escalation budget",
        "Accuracy over random (pp)",
    )
    ax.set_ylim(-0.10, 4.5)
    ax.set_yticks((0, 1, 2, 3, 4))
    for i, (x, key) in enumerate(zip(XS, CELLS)):
        value = data[key]["delta_pts"]["pooled"]
        ax.bar(x, value, width=0.29,
               color=AGGREGATE if i % 2 else SINGLE, zorder=3)
        ax.text(x, value + 0.10, number(value, 2, signed=True),
                ha="center", va="bottom", fontsize=11, color=INK)
    ax.axhline(0, color=MUTED, lw=0.8)
    save_figure(fig, "native_ablation_routing")


def write_named_values(data):
    lines = [
        "% Generated by build_native_ablation.py from the recorded 8db summary.",
        r"\begin{table}[ht]",
        r"\centering\small",
        r"\caption{Native ablation by evaluation pool. Each column is one of",
        r"the four matched LOPO readouts in Figure~\ref{fig:native-ablation}.",
        r"The lower block gives accuracy gains over random escalation in",
        r"percentage points. AUC averages weight pools equally; pooled routing",
        r"gains weight individual questions.}",
        r"\label{tab:native-ablation-values}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"& \multicolumn{2}{c}{L22} & \multicolumn{2}{c}{L35} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"Pool & Single & Aggregate & Single & Aggregate \\",
        r"\midrule",
        r"\multicolumn{5}{l}{\textit{Failure-prediction AUC}} \\",
    ]
    for pool, label in POOLS:
        lines.append(label + " & " + " & ".join(
            number(data[key]["auc"][pool]) for key in CELLS) + r" \\")
    lines += [r"\midrule", "Equal-pool mean & " + " & ".join(
        number(data[key]["auc"]["ext5_mean"]) for key in CELLS) + r" \\",
        r"\midrule",
        r"\multicolumn{5}{l}{\textit{Accuracy gain over random at a 30\% budget (pp)}} \\"]
    for pool, label in POOLS:
        lines.append(label + " & " + " & ".join(
            number(data[key]["delta_pts"][pool], 2, signed=True)
            for key in CELLS) + r" \\")
    lines += [r"\midrule", "Pooled gain & " + " & ".join(
        number(data[key]["delta_pts"]["pooled"], 2, signed=True)
        for key in CELLS) + r" \\",
        r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    (HERE / "sections/native_ablation_values.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def build():
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    if data["protocol"]["budget"] != 0.3:
        raise ValueError("The figure labels require the recorded 30% budget.")
    for key in CELLS:
        mean = sum(data[key]["auc"][p] for p, _ in POOLS) / len(POOLS)
        if abs(mean - data[key]["auc"]["ext5_mean"]) > 0.00011:
            raise ValueError(f"AUC mean disagrees with named pools: {key}")
    with plt.rc_context({
        "font.family": "DejaVu Sans", "font.size": 10,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.spines.left": False, "axes.spines.bottom": False,
        "axes.labelcolor": INK, "text.color": INK,
        "xtick.color": INK, "ytick.color": MUTED,
        "figure.facecolor": "white", "axes.facecolor": "white",
        "pdf.fonttype": 42, "ps.fonttype": 42,
    }):
        make_auc_figure(data)
        make_routing_figure(data)
    write_named_values(data)
    print(json.dumps({"source_sha256": hashlib.sha256(raw).hexdigest(),
                      "protocol": data["protocol"],
                      "auc": {k: data[k]["auc"]["ext5_mean"] for k in CELLS},
                      "routing_gain_pp": {k: data[k]["delta_pts"]["pooled"]
                                          for k in CELLS}}, indent=2))


if __name__ == "__main__":
    build()
