"""Nested evaluation of sparse score-level causal-layer fusion.

Each base head sees one layer and one causal view.  Within every outer
source-family fold, base scores for the outer-training rows are generated by
an inner source-family cross-fit.  A fixed, strongly regularized meta-head is
fit only to those out-of-fold scores; base heads are then refit on the whole
outer-training split and scored on the untouched outer test split.  This is a
stacking evaluation, not raw hidden-state concatenation, and it never writes a
gate artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedGroupKFold


RATES = (.15, .30, .50)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_npz(directory: Path, pattern: str):
    ids, arrays, paths = [], [], sorted(directory.glob(pattern))
    if not paths:
        raise FileNotFoundError(f"no {pattern} under {directory}")
    layers = None
    for path in paths:
        value = np.load(path, allow_pickle=True)
        ids.extend(str(row_id) for row_id in value["ids"])
        arrays.append(value["X"].astype(np.float32, copy=False))
        if "layers" in value:
            current = tuple(int(item) for item in value["layers"])
            if layers is not None and current != layers:
                raise RuntimeError("inconsistent layer metadata")
            layers = current
    matrix = np.concatenate(arrays)
    index = pd.DataFrame({"id": ids, "row": range(len(ids))})
    index = index.drop_duplicates("id", keep="last")
    return index.id.to_list(), matrix[index.row.to_numpy()], layers, paths


def parse_values(raw: str, cast, name: str):
    try:
        values = tuple(cast(item.strip()) for item in raw.split(",")
                       if item.strip())
    except ValueError as exc:
        raise ValueError(f"invalid {name}: {raw}") from exc
    if not values or len(set(values)) != len(values):
        raise ValueError(f"{name} must contain unique values")
    return values


def top_mask(score, rate):
    count = min(len(score), max(0, int(round(len(score) * rate))))
    mask = np.zeros(len(score), dtype=bool)
    if count:
        order = np.lexsort((np.arange(len(score)), -np.asarray(score)))
        mask[order[:count]] = True
    return mask


def routing_objective(gain, score):
    return float(np.mean([
        gain[top_mask(score, rate)].sum() / len(gain) for rate in RATES
    ]))


def macro_routing(gain, score, groups):
    return float(np.mean([
        routing_objective(gain[groups == group], score[groups == group])
        for group in sorted(set(groups))
    ]))


def macro_auc(y, score, groups):
    values = []
    for group in sorted(set(groups)):
        mask = groups == group
        if len(np.unique(y[mask])) == 2:
            values.append(roc_auc_score(y[mask], score[mask]))
    if not values:
        raise RuntimeError("no source family has both native outcome classes")
    return float(np.mean(values)), len(values)


def summary(local_ok, expert_ok, score, groups):
    y = 1 - local_ok
    if len(np.unique(y)) != 2:
        raise RuntimeError("native outcome has only one class")
    macro, valid = macro_auc(y, score, groups)
    return {
        "routing_objective_pooled": routing_objective(expert_ok - local_ok,
                                                       score),
        "routing_objective_macro_source": macro_routing(
            expert_ok - local_ok, score, groups),
        "native_failure_auc_pooled": float(roc_auc_score(y, score)),
        "native_failure_auc_macro_source": macro,
        "native_failure_valid_sources": valid,
    }


@dataclass(frozen=True)
class BaseSpec:
    layer: int
    view: str
    c: float

    @property
    def name(self):
        return f"l{self.layer}_{self.view}_c{self.c:g}"


@dataclass(frozen=True)
class MetaSpec:
    name: str
    family: str
    regularization: float


META_SPECS = (
    MetaSpec("sparse_logistic_l1_c0.05", "logistic_l1", .05),
    MetaSpec("ridge_alpha100", "ridge", 100.),
)


def feature_columns(spec: BaseSpec, layers, hidden_size):
    width = 3 * hidden_size
    start = layers.index(spec.layer) * width
    if spec.view == "full":
        return np.arange(start, start + width)
    if spec.view == "last_user":
        return np.r_[np.arange(start, start + hidden_size),
                     np.arange(start + 2 * hidden_size,
                               start + 3 * hidden_size)]
    raise ValueError(spec.view)


def fit_base(spec, layers, hidden_size, x_train, y_train, weights):
    cols = feature_columns(spec, layers, hidden_size)
    train = x_train[:, cols]
    mean = train.mean(0, dtype=np.float64).astype(np.float32)
    scale = np.maximum(train.std(0, dtype=np.float64).astype(np.float32), 1e-4)
    train = np.clip((train - mean) / scale, -10., 10.)
    model = LogisticRegression(C=spec.c, max_iter=3000, tol=1e-5)
    model.fit(train, y_train, sample_weight=weights)
    return model, mean, scale, cols


def score_base(fitted, x):
    model, mean, scale, cols = fitted
    value = np.clip((x[:, cols] - mean) / scale, -10., 10.)
    return model.predict_proba(value)[:, 1]


def cross_fitted_base_scores(specs, layers, hidden_size, x, y, weights,
                             groups, strat, folds, seed):
    scores = np.full((len(x), len(specs)), np.nan, dtype=np.float64)
    splitter = StratifiedGroupKFold(folds, shuffle=True, random_state=seed)
    for train, valid in splitter.split(x, strat, groups):
        if len(np.unique(y[train])) != 2:
            raise RuntimeError("inner base-head training fold has one class")
        for column, spec in enumerate(specs):
            fitted = fit_base(spec, layers, hidden_size, x[train], y[train],
                              weights[train])
            scores[valid, column] = score_base(fitted, x[valid])
    if not np.isfinite(scores).all():
        raise RuntimeError("inner cross-fit did not score every row")
    return scores


def refit_base_scores(specs, layers, hidden_size, x_train, y_train, weights,
                      x_test):
    output = np.empty((len(x_test), len(specs)), dtype=np.float64)
    for column, spec in enumerate(specs):
        fitted = fit_base(spec, layers, hidden_size, x_train, y_train, weights)
        output[:, column] = score_base(fitted, x_test)
    return output


def fit_meta(spec, train, y, weights):
    mean = train.mean(0)
    scale = np.maximum(train.std(0), 1e-6)
    z = (train - mean) / scale
    if spec.family == "logistic_l1":
        model = LogisticRegression(
            penalty="l1", solver="liblinear",
            C=spec.regularization,
            max_iter=3000, tol=1e-6)
        model.fit(z, y, sample_weight=weights)
    elif spec.family == "ridge":
        model = Ridge(alpha=spec.regularization)
        model.fit(z, y, sample_weight=weights)
    else:
        raise ValueError(spec.family)
    return model, mean, scale


def score_meta(spec, fitted, test):
    model, mean, scale = fitted
    z = (test - mean) / scale
    if spec.family == "logistic_l1":
        return model.predict_proba(z)[:, 1]
    return model.predict(z)


def meta_receipt(spec, fitted, base_specs):
    model, mean, scale = fitted
    coef = np.asarray(model.coef_).reshape(-1)
    return {
        "spec": asdict(spec),
        "intercept": float(np.asarray(model.intercept_).reshape(-1)[0]),
        "standardization_mean": mean.tolist(),
        "standardization_scale": scale.tolist(),
        "coefficients": {base.name: float(value)
                         for base, value in zip(base_specs, coef)},
        "nonzero_coefficients": int(np.count_nonzero(np.abs(coef) > 1e-12)),
    }


def artifact_score(path: Path, x):
    artifact = json.loads(path.read_text())
    weights = np.asarray(artifact["w"], dtype=np.float32)
    if x.shape[1] != len(weights):
        raise RuntimeError(
            f"live artifact expects {len(weights)} features, got {x.shape[1]}")
    return x @ weights + float(artifact["b"])


def deltas(candidate, baseline):
    keys = ("routing_objective_pooled", "routing_objective_macro_source",
            "native_failure_auc_pooled", "native_failure_auc_macro_source")
    return {key: candidate[key] - baseline[key] for key in keys}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--selection", type=Path, required=True)
    parser.add_argument("--causal-dir", type=Path, required=True)
    parser.add_argument("--original-dir", type=Path, required=True)
    parser.add_argument("--local", type=Path, required=True)
    parser.add_argument("--expert", type=Path, required=True)
    parser.add_argument("--live-artifact", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--layers", default="18,22,26,30")
    parser.add_argument("--base-cs", default="0.0001")
    parser.add_argument("--hidden-size", type=int, default=4096,
                        help=argparse.SUPPRESS)
    parser.add_argument("--outer-folds", type=int, default=5,
                        help=argparse.SUPPRESS)
    parser.add_argument("--inner-folds", type=int, default=3,
                        help=argparse.SUPPRESS)
    args = parser.parse_args()

    layers_requested = parse_values(args.layers, int, "layers")
    base_cs = parse_values(args.base_cs, float, "base Cs")
    if len(base_cs) > 2 or any(value <= 0 for value in base_cs):
        raise ValueError("base Cs must contain one or two positive values")
    if args.hidden_size <= 0 or args.outer_folds < 2 or args.inner_folds < 2:
        raise ValueError("hidden size and fold counts must be positive")

    causal_ids, causal, layers, causal_paths = load_npz(
        args.causal_dir, "causal_prefill_feats.rank*.npz")
    original_ids, original, _, original_paths = load_npz(
        args.original_dir, "prospective_native_feats.rank*.npz")
    if layers != layers_requested:
        raise RuntimeError(f"expected layers {layers_requested}, got {layers}")
    expected = len(layers) * 3 * args.hidden_size
    if causal.shape[1] != expected or not np.isfinite(causal).all():
        raise RuntimeError(f"invalid causal feature matrix {causal.shape}")
    causal_index = {row_id: i for i, row_id in enumerate(causal_ids)}
    original_index = {row_id: i for i, row_id in enumerate(original_ids)}

    frame = pd.read_parquet(args.selection).drop_duplicates("id")
    if "mode" in frame:
        frame = frame[frame["mode"] == "standalone"]
    local = pd.read_parquet(args.local).drop_duplicates("id", keep="last")
    expert = pd.read_parquet(args.expert).drop_duplicates("id", keep="last")
    frame = frame.merge(local[["id", "adequate"]].rename(
        columns={"adequate": "local_ok"}), on="id", validate="one_to_one")
    frame = frame.merge(expert[["id", "adequate"]].rename(
        columns={"adequate": "expert_ok"}), on="id", validate="one_to_one")
    frame = frame[frame.id.astype(str).isin(causal_index) &
                  frame.id.astype(str).isin(original_index)]
    frame = frame.sort_values("id").reset_index(drop=True)
    x = np.stack([causal[causal_index[str(row_id)]] for row_id in frame.id])
    xo = np.stack([original[original_index[str(row_id)]] for row_id in frame.id])
    local_ok = frame.local_ok.astype(int).to_numpy()
    expert_ok = frame.expert_ok.astype(int).to_numpy()
    if set(np.unique(local_ok)) - {0, 1} or set(np.unique(expert_ok)) - {0, 1}:
        raise RuntimeError("outcomes must be binary")
    y = 1 - local_ok
    gain = expert_ok - local_ok
    weights = np.where(gain < 0, 2., 1.)
    groups = frame.source_family.astype(str).to_numpy()
    strat = (gain + 1) * 2 + y
    live = artifact_score(args.live_artifact, xo)

    base_specs = tuple(BaseSpec(layer, view, c) for layer in layers
                       for view in ("full", "last_user") for c in base_cs)
    outer = StratifiedGroupKFold(
        args.outer_folds, shuffle=True, random_state=42)
    nested = {spec.name: np.full(len(frame), np.nan) for spec in META_SPECS}
    outer_rows = []
    for fold, (train, test) in enumerate(outer.split(x, strat, groups)):
        train_oof = cross_fitted_base_scores(
            specs=base_specs, layers=layers, hidden_size=args.hidden_size,
            x=x[train], y=y[train], weights=weights[train],
            groups=groups[train], strat=strat[train],
            folds=args.inner_folds, seed=100 + fold)
        test_scores = refit_base_scores(
            base_specs, layers, args.hidden_size, x[train], y[train],
            weights[train], x[test])
        row = {"outer_fold": fold,
               "test_groups": sorted(set(groups[test])), "meta_heads": {}}
        for meta_spec in META_SPECS:
            fitted = fit_meta(meta_spec, train_oof, y[train], weights[train])
            nested[meta_spec.name][test] = score_meta(
                meta_spec, fitted, test_scores)
            row["meta_heads"][meta_spec.name] = {
                "fit": meta_receipt(meta_spec, fitted, base_specs),
                "test": summary(local_ok[test], expert_ok[test],
                                  nested[meta_spec.name][test], groups[test]),
            }
        outer_rows.append(row)
        print(f"outer={fold} train={len(train)} test={len(test)}", flush=True)

    if any(not np.isfinite(score).all() for score in nested.values()):
        raise RuntimeError("outer cross-fit did not score every row")
    live_summary = summary(local_ok, expert_ok, live, groups)
    summaries = {"live": live_summary}
    comparisons = {}
    strata = {}
    for meta_spec in META_SPECS:
        name, score = meta_spec.name, nested[meta_spec.name]
        summaries[name] = summary(local_ok, expert_ok, score, groups)
        comparisons[name] = deltas(summaries[name], live_summary)
        strata[name] = {}
        for column in ("language", "pool"):
            values = frame[column].astype(str).to_numpy()
            strata[name][column] = {}
            for value in sorted(set(values)):
                mask = values == value
                candidate = routing_objective(gain[mask], score[mask])
                baseline = routing_objective(gain[mask], live[mask])
                strata[name][column][value] = {
                    "rows": int(mask.sum()), "candidate_routing": candidate,
                    "live_routing": baseline, "delta": candidate - baseline,
                }

    primary = META_SPECS[0].name
    primary_delta = comparisons[primary]
    gates = {
        "macro_routing_delta_ge_0.005":
            primary_delta["routing_objective_macro_source"] >= .005,
        "pooled_routing_nonnegative":
            primary_delta["routing_objective_pooled"] >= 0,
        "macro_native_auc_delta_ge_0.010":
            primary_delta["native_failure_auc_macro_source"] >= .01,
        "pooled_native_auc_nonnegative":
            primary_delta["native_failure_auc_pooled"] >= 0,
        "language_routing_nonnegative": all(
            row["delta"] >= 0
            for row in strata[primary]["language"].values()),
        "broad_pool_routing_ge_minus_0.010": all(
            row["delta"] >= -.01
            for row in strata[primary]["pool"].values()),
    }

    result = {
        "status": "p26_sparse_causal_score_fusion_development",
        "inputs": {
            "rows": len(frame),
            "source_families": int(frame.source_family.nunique()),
            "layers": layers, "causal_dimension": x.shape[1],
            "selection_sha256": sha256(args.selection),
            "local_sha256": sha256(args.local),
            "expert_sha256": sha256(args.expert),
            "live_artifact_sha256": sha256(args.live_artifact),
            "causal_files": [{"path": str(path), "sha256": sha256(path)}
                             for path in causal_paths],
            "original_files": [{"path": str(path), "sha256": sha256(path)}
                               for path in original_paths],
        },
        "protocol": {
            "outer_folds": args.outer_folds,
            "inner_folds": args.inner_folds,
            "grouping": "source_family",
            "base_target": "native_failure",
            "base_training_scores": "inner out-of-fold only",
            "outer_test_scores": "base heads refit on complete outer train",
            "meta_hyperparameters": "fixed before evaluation; no selection",
            "primary_meta_head": primary,
            "frozen_gates": {
                "macro_routing_delta": ">= 0.005",
                "pooled_routing_delta": ">= 0",
                "macro_native_auc_delta": ">= 0.010",
                "pooled_native_auc_delta": ">= 0",
                "each_language_routing_delta": ">= 0",
                "each_pool_routing_delta": ">= -0.010",
            },
            "development_only": True,
            "pass_action": "causally recapture frozen P22 and P23 only",
        },
        "base_specs": [asdict(spec) | {"name": spec.name}
                       for spec in base_specs],
        "meta_specs": [asdict(spec) for spec in META_SPECS],
        "outer_folds": outer_rows,
        "summaries": summaries,
        "deltas_vs_live": comparisons,
        "strata": strata,
        "primary_gates": gates,
        "advance_to_p22_p23_causal_recapture": bool(all(gates.values())),
        "live_unchanged": True,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps({"summaries": summaries,
                      "deltas_vs_live": comparisons,
                      "primary_gates": gates,
                      "advance": result[
                          "advance_to_p22_p23_causal_recapture"]},
                     indent=2), flush=True)


if __name__ == "__main__":
    main()
